// src/components/planner/step-itinerary.tsx
'use client'
import { ChevronUp, ChevronDown, MapPin, Clock } from 'lucide-react'
import { usePlannerStore } from '@/stores/planner-store'
import { destinations } from '@/lib/data/destinations'
import { getItemById } from '@/lib/data/itinerary-items'
import { getStartingLocationById } from '@/lib/data/starting-locations'

export function StepItinerary() {
  const {
    orderedDestinationSlugs,
    selectedActivityIds,
    durationDays,
    startingLocationId,
    reorderDestination,
    nextStep,
    prevStep,
  } = usePlannerStore()

  const startLoc = getStartingLocationById(startingLocationId)

  // Distribute days evenly across destinations
  const daysPerDest = Math.max(
    1,
    Math.floor(durationDays / Math.max(orderedDestinationSlugs.length, 1)),
  )
  const extraDays = durationDays - daysPerDest * orderedDestinationSlugs.length

  return (
    <div className="space-y-6">
      {/* Route header */}
      <div className="bg-brand-navy-900 rounded-2xl p-5 text-white">
        <p className="text-brand-amber-400 text-xs font-semibold uppercase tracking-wider mb-2">
          Suggested Route
        </p>
        <div className="flex flex-wrap items-center gap-2 text-sm font-medium">
          {startLoc && (
            <>
              <span className="flex items-center gap-1 text-white/80">
                <MapPin className="w-3.5 h-3.5 text-brand-orange-400" />
                {startLoc.name}
              </span>
              <span className="text-brand-navy-500">→</span>
            </>
          )}
          {orderedDestinationSlugs.map((slug, i) => {
            const dest = destinations.find((d) => d.slug === slug)
            return (
              <span key={slug} className="flex items-center gap-2">
                <span className="text-white">{dest?.name ?? slug}</span>
                {i < orderedDestinationSlugs.length - 1 && (
                  <span className="text-brand-navy-500">→</span>
                )}
              </span>
            )
          })}
        </div>
        <p className="text-brand-navy-400 text-xs mt-3">
          Auto-generated by shortest route from your starting location. Use the arrows to adjust.
        </p>
      </div>

      {/* Day-by-day blocks */}
      <div className="space-y-4">
        {orderedDestinationSlugs.map((slug, index) => {
          const dest = destinations.find((d) => d.slug === slug)
          const activities = (selectedActivityIds[slug] ?? [])
            .map((id) => getItemById(id))
            .filter(Boolean) as ReturnType<typeof getItemById>[]
          const days = daysPerDest + (index === 0 ? extraDays : 0)
          const dayStart = orderedDestinationSlugs
            .slice(0, index)
            .reduce((acc, s, i) => acc + daysPerDest + (i === 0 ? extraDays : 0), 1)

          return (
            <div key={slug} className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
              {/* Destination header */}
              <div className="flex items-center justify-between p-4 sm:p-5 border-b border-gray-50">
                <div>
                  <div className="flex items-center gap-2 mb-0.5">
                    <span className="text-xs font-semibold text-brand-orange-500 bg-brand-orange-50 px-2 py-0.5 rounded-full">
                      Day {dayStart}{days > 1 ? `–${dayStart + days - 1}` : ''} · {days} {days === 1 ? 'day' : 'days'}
                    </span>
                  </div>
                  <h3 className="font-extrabold text-brand-navy-900 text-base">{dest?.name}</h3>
                  <p className="text-brand-navy-400 text-xs italic">{dest?.tagline}</p>
                </div>

                {/* Reorder arrows */}
                <div className="flex flex-col gap-1 shrink-0">
                  <button
                    type="button"
                    onClick={() => index > 0 && reorderDestination(index, index - 1)}
                    disabled={index === 0}
                    className="w-7 h-7 rounded-lg border border-gray-200 flex items-center justify-center text-brand-navy-400 hover:border-brand-orange-400 hover:text-brand-orange-500 disabled:opacity-25 disabled:cursor-not-allowed transition-colors"
                  >
                    <ChevronUp className="w-4 h-4" />
                  </button>
                  <button
                    type="button"
                    onClick={() => index < orderedDestinationSlugs.length - 1 && reorderDestination(index, index + 1)}
                    disabled={index === orderedDestinationSlugs.length - 1}
                    className="w-7 h-7 rounded-lg border border-gray-200 flex items-center justify-center text-brand-navy-400 hover:border-brand-orange-400 hover:text-brand-orange-500 disabled:opacity-25 disabled:cursor-not-allowed transition-colors"
                  >
                    <ChevronDown className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Activities list */}
              {activities.length > 0 ? (
                <ul className="divide-y divide-gray-50">
                  {activities.map((item) => item && (
                    <li key={item.id} className="flex items-center justify-between px-5 py-3 text-sm">
                      <span className="text-brand-navy-700 font-medium">{item.name}</span>
                      <span className="flex items-center gap-2 text-brand-navy-400 text-xs shrink-0 ml-4">
                        <Clock className="w-3 h-3" />
                        {item.durationHours}h
                        <span className="font-semibold text-brand-orange-500">${item.priceUsd}</span>
                      </span>
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="px-5 py-3 text-xs text-brand-navy-400 italic">No activities selected — free exploration.</p>
              )}
            </div>
          )
        })}
      </div>

      {/* Nav */}
      <div className="flex items-center justify-between pt-2">
        <button
          type="button"
          onClick={prevStep}
          className="px-6 py-2.5 rounded-xl border border-gray-200 text-sm font-semibold text-brand-navy-700 hover:border-brand-orange-300 transition-colors"
        >
          ← Back
        </button>
        <button
          type="button"
          onClick={nextStep}
          className="px-8 py-2.5 rounded-xl bg-brand-orange-500 text-white font-bold text-sm hover:bg-brand-orange-600 transition-colors shadow-md"
        >
          Choose Accommodation →
        </button>
      </div>
    </div>
  )
}
